
// Generated by SyntheticDataGenerator 1.0.0 (Wednesday, May 3rd 2023, 9:40:13 pm)
import { SyntheticDataGenerator, Interface } from "./SyntheticDataGenerator";
import * as faker from "@faker-js/faker";

export enum Person_Sex_enum { Male,Female }
export enum Person_EyeColor_enum { Blue,Green,Brown,Hazel }
export interface Person extends Interface { FirstName: string,LastName: string,Age: number,Sex: Person_Sex_enum,PhoneNumber: string,EyeColor: Person_EyeColor_enum }
    
export class person_generator extends SyntheticDataGenerator{
    constructor(){
        super()
    }


    Generate(f: string | Interface, q: number): any {
        super._Generate(f, q);
    }

    GenerateWithMutator(f: string | Interface, m: any[], c: number): any {
        super._GenerateWithMutator(f, m, c);
    }
}

function Main () {
    const p: person_generator = new person_generator();
    const exec = p.Generate || p.GenerateWithMutator;
}